### ISSUE TITLE
Cannot find module 'msw/node' in Jest test after upgrading to v2

### ISSUE THREAD

**Issue by mbaumanndev** [kettanaito/msw#1787]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v18.14.2

### Reproduction repository

https://github.com/mbaumanndev/msw-issue-repro

### Reproduction steps

On the repo:

```
yarn install --immutable
yarn test
```

Importing `msw/node` cause an error in Jest.

Note that this is an extract from my dev env on a project where it was working with msw 1.3.2 and where I followed the upgrade guide.

### Current behavior

```
Test suite failed to run

    Cannot find module 'msw/node' from 'src/jestUtils.ts'

    Require stack:
      src/jestUtils.ts
      src/sample.test.tsx

      1 | import { DefaultBodyType, Path, PathParams, ResponseResolver, http } from 'msw'
    > 2 | import { setupServer } from 'msw/node'
        | ^
      3 | import { HttpRequestResolverExtras } from 'msw/lib/core/handlers/HttpHandler'
      4 |
      5 | export interface ServerEndoint {

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.require (src/jestUtils.ts:2:1)
      at Object.require (src/sample.test.tsx:2:1)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.867 s, estimated 1 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected behavior

The test should pass since Jest should be able to import `msw/node`

**Comment by mbaumanndev** [comment]
Related to #1786

**Comment by kettanaito** [comment]
Thanks for reporting this.

- [Detailed explanation of why this happens](https://github.com/mswjs/msw/issues/1786#issuecomment-1782559851)
- [Documentation on how to fix this](https://mswjs.io/docs/migrations/1.x-to-2.x#cannot-find-module-mswnode-jsdom)
