### ISSUE TITLE
`whatwg-fetch` requests don't clear when server is `close()`d, leading to an error

### ISSUE THREAD

**Issue by elado** [kettanaito/msw#1684]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.18.0

### Reproduction repository

https://github.com/elado/msw-fetch-error

### Reproduction steps

In the readme of the repo https://github.com/elado/msw-fetch-error

Basically in a jest + jsdom + whatwg-fetch, requests that start but don't finish before the test is done cause an error.

### Current behavior

When using `whatwg-fetch` and starting a request without waiting for it inside a test, the test passes, but then there's a node error with exit code 1.

```js
test("starts a request", () => {
  fetch("http://localhost/users"); // no await!
});
```

Error:

```
/path/to/msw-fetch-error/node_modules/jsdom/lib/jsdom/browser/Window.js:376
      return idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)._location);
                                                                              ^

TypeError: Cannot read properties of null (reading '_location')
    at Window.get location [as location] (/path/to/msw-fetch-error/node_modules/jsdom/lib/jsdom/browser/Window.js:376:79)
    at FetchInterceptor.<anonymous> (/path/to/msw-fetch-error/node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:52:9)
    at step (/path/to/msw-fetch-error/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:59:23)
    at Object.next (/path/to/msw-fetch-error/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:40:53)
    at fulfilled (/path/to/msw-fetch-error/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:31:58)
```

MSW is trying to access `new URL` which uses `location` intenally, after jsdom has disposed the window object.

```js
requestUrl = new URL(
 url,
 typeof location !== "undefined" ? location.origin : undefined
);
```

This doesn't happen with `node-fetch` or `axios`. `node-fetch` expect full URLs which requires a big migration of our codebase.

The MSW+jest examples show usage of `whatwg-fetch`.

### Expected behavior

Have `server.close()` shut down also in progress `whatwg-fetch` requests, like it does with `node-fetch`/`axios`.

Looks like the culprit code was reworked in `@mswjs/interceptors@0.23.0` and is unreleased. Attempting to use that version with the most recent `msw@1.2.3` doesn't work (errors on missing imports).

**Comment by kettanaito** [comment]
Hi, @elado. Thanks for reporting this.

Full disclosure, MSW doesn't currently abort any requests when `server.close()` is called, neither `whatwg-fetch` nor `node-fetch` or `axios`. I believe the difference in behavior you're experiencing is primarily caused by the difference of implementation between those libraries. 

That being said, I do think this is addressed in the latest Interceptors. Could you try `msw@next` and see if the issue is still there? Learn more in #1464.

**Comment by elado** [comment]
Thanks for your answer! I see; I thought `.close()` would abort the requests/ignore the responses because they go through the internal mocked fetch (I noticed it doesn't use the `pureFetch` when they match a handler). But I assume that the development on that version has halted in favor of `@next`.

I am upgrading from `^0.39.2` and this issue didn't happen there, likely because there was no `new URL` call after the test was finished.
`@next` requires Node 18 which is not something we can immediately upgrade, plus with my test repo I get `Cannot find module 'msw/node' from 'src/server.js'`.

At this point I'll consider either staying on `0.39.2`, patch `1.2.3`, or upgrade Node+wait for the `next` version.

**Comment by sgoodrow-zymergen** [comment]
> At this point I'll consider either staying on `0.39.2`, patch `1.2.3`, or upgrade Node+wait for the `next` version.

Can you confirm `1.2.3` is the version you're using that doesn't have this problem? I tried to downgrade and still had it with that version.

**Comment by VictorJSV** [comment]
> Can you confirm `1.2.3` is the version you're using that doesn't have this problem? I tried to downgrade and still had it with that version.

I downgrade to `1.2.3` and still problem, but with `0.47.3` it works!

**Comment by kettanaito** [comment]
Thanks once again for the discussion around this. As of MSW 2.0, you don't need (and mustn't be using) any fetch polyfills to use MSW. It requires Node.js v18+, which will require a migration effort, alongside the [MSW 2.0 Migration guidelines](https://mswjs.io/docs/migrations/1.x-to-2.x). That is the effort worth taking. Node.js v16 is discontinued. 

There are no plans to address polyfill-specific issues anymore. Thankfully, we can leave the polyfill era behind and finally use the standard JavaScript everywhere.
