### ISSUE TITLE
2.4.0 Main entry point still exports handlers (i.e: `GraphQLHandler`)

### ISSUE THREAD

**Issue by nartc** [kettanaito/msw#2247]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

20.14.0

### Reproduction repository

https://github.com/nartc/msw-entry-point-bug

### Reproduction steps

`npm install`
`npm test`

Script fails with `Cannot find module "graphql"` 

### Current behavior

Thank you for your effort on `msw`.

Before I say anything, I believe our issue is our own "user error". However, I also believe this issue can still be an overlook as current code would break at runtime with 2.4.0 and the release note does not mention anything about the new secondary entry points available in 2.4.0

```ts
import { http, HttpHandler } from 'msw';
```

This works in pre 2.4.0 but will break in 2.4.0 for projects that don't have `graphql` installed. This is due to `msw` core entry point still exports the handlers which makes `graphql` **NOT** an optional peer dependency.

The proper fix would be to import from `msw/core/http` but it seems like `msw/core/http` does not export `HttpHandler` either.

Once again, our project runs into this due to many errors/mistakes on our part but I want to raise this issue in case others run into the same thing (or have the same user errors/mistakes)

### Expected behavior

```ts
import { http } from 'msw';
```

This import should at least break at compilation time (type checking time) with something like: msw does not export `http`. And release note should mention migrating to `msw/core/http` (or respective entry point for the handlers).

**Comment by ghost91-** [comment]
Unfortunately, using more specific exports doesn't always seem to be possible. For example, unless I am mistaken, `delay` is only exported via the main export.

Similarly, `HttpResponse` also is not exported from `msw/core/http`. Probably applies to quite a few more things.

If `msw/core/http` is really intended as the "don't need graphql" entrypoint, the exports should probably be identical to those of `msw`, except from the graphql related stuff.

**Comment by nartc** [comment]
@ghost91- or `msw` entry point should be cleared of anything that requires optional peer dependencies so things like main utilities can still be exported from the main entry point.

**Comment by kettanaito** [comment]
@ghost91-, good point. The explicit import would be better once we drop `graphql` export from the root module. So you import graphl from `msw/core/graphql` only. 

For now, I think the safest way to fix this and now force developers to install graphql is to make that import dynamic. Need to give this a try.

**Comment by kettanaito** [comment]
I will close this one in favor of #2248 (has a more searchable error message). Please keep track of the updates there. Thanks.

**Comment by kettanaito** [comment]
## Released: v2.4.1 🎉

This has been released in v2.4.1!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.4.1)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.4.1)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
